### ISSUE TITLE
Can you provide your log file?

### ISSUE THREAD

**Issue by Hiusam** [TuSimple/SST#12]
Hi, can you provide your log file so that I can find out whether my training process is correct? Thank you very much.

**Comment by Abyssaledge** [comment]
Some of them are not available for now, I hope the following one could help you. 
[sst_waymoD5_1x_3class_12heads_20211213_125107.log](https://github.com/TuSimple/SST/files/8103607/sst_waymoD5_1x_3class_12heads_20211213_125107.log)

**Comment by Hiusam** [comment]
Great! Thank you.
