### ISSUE TITLE
Questions about SSTInputlayer

### ISSUE THREAD

**Issue by JiaxinZhuang** [TuSimple/SST#14]
Hi~ I run run.sh, its configs use SSTInputlayer, which is fed with three parameters as below. However, the definition of forward function for SSTInputlayer (not SSTInputlayer v2) only contains two parameters. The code ran well without any error, which I can't figure out why.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/25994409/155644320-00da24d9-6fbd-4419-8ac7-504f14f0929d.png">

<img width="750" alt="image" src="https://user-images.githubusercontent.com/25994409/155644503-cacb782e-e812-49e2-a240-b1edb1ff32ea.png">

**Comment by Abyssaledge** [comment]
Hi, thanks for using. I use `SSTInputLayerV2` In `run.sh` in current version. I wonder which config do you use in your `run.sh`?

**Comment by JiaxinZhuang** [comment]
Thanks for your reply, I used sst_waymoD5_1x_ped_cyc_8heads_3f.
