### ISSUE TITLE
Hyperparameter settings in SST

### ISSUE THREAD

**Issue by lihao0374** [TuSimple/SST#22]
Great job.

I still have a few questions and look forward to your answers:
    If I want to try SST on a dataset with low density （LiDAR with 32 lasers）, how should I modify the  hyperparameters in SST.
    If I use a smaller voxel size (0.16, 0.16, 6), how should I adjust the hyperparameters in SST, such as drop info, window shape settings and so on?

**Comment by Abyssaledge** [comment]
Although I have not tried this setting, my suggestions are (in the refactored version):
```
window_shape = (20, 20, 1) ~ (24, 24, 1)
drop_info  = {
    0:{'max_tokens':30, 'drop_range':(0, 30)},
    1:{'max_tokens':60, 'drop_range':(30, 60)},
    2:{'max_tokens':100, 'drop_range':(60, 100)},
    3:{'max_tokens':150, 'drop_range':(100, 1000)},
}
```
Remember to change the `sparse_shape` according to your point cloud range and voxelization size.
And if I were you, I might draw the distribution of the number of pillars in a window to determine the drop_info.

**Comment by lihao0374** [comment]
> Thank you for your reply. 

In addition, I notice that only 'x,y,z' of points are used during training, and the intensity information in Waymo dataset is not used. What is the reason for this？

**Comment by Abyssaledge** [comment]
The intensity in Waymo is not normalized, using them directly may lead to NaN output. It's fine to use it If you clip or normalize it into a reasonable range.
