### ISSUE TITLE
ingroup_indices

### ISSUE THREAD

**Issue by seonhoon1002** [TuSimple/SST#34]
I have a import problem of ingroup_indices in "mmdet3d>ops>sst>sst_ops.py, line 197"
I try to fix it, but I can't find what is the "ingroup_indices" and where is it.
If you have a solution, please notice how can I fix it.

**Comment by Abyssaledge** [comment]
Solved in #31 .

**Comment by seonhoon1002** [comment]
I should install "torchEx" which you make for the cuda, and I can solve this problem. Thanks: )
