### ISSUE TITLE
Question about voxel coors

### ISSUE THREAD

**Issue by abhinavrai44** [TuSimple/SST#35]
The voxel coors are described as [b, z, y, x] here -  https://github.com/TuSimple/SST/blob/712d98072b41643c38e72a7c9564fbe68bcc813c/mmdet3d/models/middle_encoders/sst_input_layer.py#L56

Sorry for the noob question but what does the symbol b mean here.

Thanks

**Comment by Abyssaledge** [comment]
It indicates the batch indices (sample ID the voxels belong to).
