### ISSUE TITLE
Question about Lidar frame

### ISSUE THREAD

**Issue by tdzdog** [TuSimple/SST#37]
I see you provide 3-frame results in the paper. Do you use the multiple frames in both training and validation? How about training the model with a single frame but validating the model with 3 frames?

**Comment by Abyssaledge** [comment]
Sorry for late reply. Although we have not try this strategy, I thought this might lead to inconsistency between training and inference. As a compromise, it might be better to training with two random frames and testing with all frames (similar to activation dropout).
