### ISSUE TITLE
waymo validation set Eval problem

### ISSUE THREAD

**Issue by xieyunjiao-holo** [TuSimple/SST#39]
Hello, dear friend, I completed the training of waymo datasets, but an error was reported in the verification part, showing that the file could not be found. I did not find the compute_detection_metrics_main related files under the SST folder.
How to solve this please?
Next, how to skip the training and just do the evaluation on the validation set? 

![image](https://user-images.githubusercontent.com/99383669/175241729-4c71c6d5-d9bc-47f4-a98d-e763c50bdc7f.png)

![image](https://user-images.githubusercontent.com/99383669/175241836-6179e45d-451f-4b51-bff6-6382ed0945dc.png)

**Comment by Abyssaledge** [comment]
`compute_detection_metrics_main` is built from WOD source code. Please follow their [instructions](https://github.com/waymo-research/waymo-open-dataset)
And the docs in MMDetection3D might help: https://mmdetection3d.readthedocs.io/en/latest/datasets/waymo_det.html.

**Comment by Abyssaledge** [comment]
I am not sure what the `pkl`  refers to. MMDetection3D will automatically save a `pkl` file and convert it to `bin`, you do not need to  convert it yourself.

**Comment by JuiceLemonLemon** [comment]
> 

@xieyunjiao-holo 
Hello, it's good to see you.
How do you implement model evaluation code, could you please share it to me?

**Comment by Abyssaledge** [comment]
@JuiceLemonLemon  You could follow this to build the evaluation tool: https://github.com/Abyssaledge/waymo-open-dataset-master/blob/master/docs/quick_start.md#local-compilation-without-docker-system-requirements

Besides, I provide a faster version here: https://github.com/Abyssaledge/waymo-open-dataset-master, which produces the same results with WOD official repo but much faster.

**Comment by JuiceLemonLemon** [comment]
> @JuiceLemonLemon You could follow this to build the evaluation tool: https://github.com/Abyssaledge/waymo-open-dataset-master/blob/master/docs/quick_start.md#local-compilation-without-docker-system-requirements
> 
> Besides, I provide a faster version here: https://github.com/Abyssaledge/waymo-open-dataset-master, which produces the same results with WOD official repo but much faster.

Thank you for your quick reply.
Bazel installation is too hard for me, our server cannot download from network, and have no JAVA. So I tried to install Bazel, but failed.

**Comment by JuiceLemonLemon** [comment]
> 



> @JuiceLemonLemon You could follow this to build the evaluation tool: https://github.com/Abyssaledge/waymo-open-dataset-master/blob/master/docs/quick_start.md#local-compilation-without-docker-system-requirements
> 
> Besides, I provide a faster version here: https://github.com/Abyssaledge/waymo-open-dataset-master, which produces the same results with WOD official repo but much faster.

I have finished to build the evaluation tool and got the waymo evaluation results, thank you very much.

**Comment by leap233** [comment]
> > 
> 
> > [@JuiceLemonLemon](https://github.com/JuiceLemonLemon) You could follow this to build the evaluation tool: https://github.com/Abyssaledge/waymo-open-dataset-master/blob/master/docs/quick_start.md#local-compilation-without-docker-system-requirements
> > Besides, I provide a faster version here: https://github.com/Abyssaledge/waymo-open-dataset-master, which produces the same results with WOD official repo but much faster.
> 
> I have finished to build the evaluation tool and got the waymo evaluation results, thank you very much.

hi, How did you successfully evaluate the Waymo dataset? I've made numerous efforts but still encounter errors. Could you please share the detailed steps with me? Thank you.

**Comment by leap233** [comment]
> > `compute_detection_metrics_main` is built from WOD source code. Please follow their [instructions](https://github.com/waymo-research/waymo-open-dataset) And the docs in MMDetection3D might help: https://mmdetection3d.readthedocs.io/en/latest/datasets/waymo_det.html.
> 
> Thanks! I implemented model evaluation. But there is still a question about the evaluation. Where is the code to convert the test results from pkl to bin please? Thank you very much .

hi, How did you successfully evaluate the Waymo dataset? I've made numerous efforts but still encounter errors. Could you please share the detailed steps with me? Thank you.
