### ISSUE TITLE
Question regarding Region Batching

### ISSUE THREAD

**Issue by abhinavrai44** [TuSimple/SST#40]
The paper says that due to sparsity of pointclouds the number of valid tokens can vary. However, in the function [drop_voxel](https://github.com/TuSimple/SST/blob/main/mmdet3d/models/middle_encoders/sst_input_layer_v2.py#L77) the features do not seem to be used. 

Is my assumption that DynamicVFE voxel encoder already filters the voxels that are just filled with zeros, and hence the number of voxels input to SSTInputLayer every time can vary is correct ?

**Comment by Abyssaledge** [comment]
The number of valid tokens in SSTInputLayer varies between iterations. The `drop_voxel` function is to avoid the cases that too much tokens in a region leads to the `out of memory` error.
