### ISSUE TITLE
About configuration question

### ISSUE THREAD

**Issue by seonhoon1002** [TuSimple/SST#42]
Hello, I have two questions about your codes.
1. In comments on config files in the D5 series, "D5 in the config name means the whole dataset is divided into 5 folds, We only use one fold for efficient experiments."
So this means that it uses 20% of the waymo dataset?
2. There are 5dim in configs, what is the mean of 5dim in lidar?

Summary
1. What is the mean of D5 in config files?
2. What is the mean of 5dim in config files in lidar?

**Comment by Abyssaledge** [comment]
1. D5 means that sample 1 frame every 5 frames, which builds a sub training dataset containing 20% data.
2. 5dim means that use intensity and elongation as extra point features in addition to xyz.

**Comment by seonhoon1002** [comment]
And I have an additional question about D5.

When I analyzed between "waymo-3d-3class" and "waymoD5-3d-3class" in "confgs/_base_/datasets", It seems like that only difference between two codes is setting of "use_dim" in "train/test/eval_pipeline">'LoadPointsFromFile"

Does "use_dim" makes difference for D5 and D1?

![use_dim](https://user-images.githubusercontent.com/41002216/178204311-50f11d13-4a52-498d-a20f-b3c1f919aa58.png)

**Comment by Abyssaledge** [comment]
`use_dim` has nothing to do with `load_interval`. The names of data config file are a little bit confusing, so you should focus on the `load_interval` in a config file instead of its name.

**Comment by seonhoon1002** [comment]
So does the below part control interval?
![use_dim](https://user-images.githubusercontent.com/41002216/178208853-170190cd-9dd6-49bc-87fe-4da4c5a217cc.png)

**Comment by Abyssaledge** [comment]
Yes

**Comment by seonhoon1002** [comment]
Aha! I see, Thanks!!
