### ISSUE TITLE
Do you use the whole Waymo datasets?

### ISSUE THREAD

**Issue by Hiusam** [TuSimple/SST#9]
Hi, I like your good work!!!!
I want to ask do you use the whole Waymov1.2 dataset or use the subset that is subsampled every five frames like that in [MMDetection3D-Waymo-Training](https://mmdetection3d.readthedocs.io/zh_CN/latest/datasets/waymo_det.html#id2)?

**Comment by Abyssaledge** [comment]
Our best models use the whole WOD. We also provide configs with 20% data size.

**Comment by ziqipang** [comment]
@Hiusam Please see the answer above.

**Comment by Hiusam** [comment]
OK. Thank you. Happy Chinese New Year!
